[Theme]
name=Cute
version=1.0
description=A cute Communi theme
maintainer=J-P Nurmi <jpnurmi@gmail.com>

[Resources]
prefix=:/themes/cute

[StyleSheets]
document=:/themes/cute/cute.css
application=:/themes/cute/cute.qss

[QPalette]
TreeBadge/text=#ffffff
TreeBadge/background=palette(dark)
TreeBadge/highlight=#ff8080
TreeBadge/highlighted-text=#ffffff
TreeItem/highlighted-text=#ff4040
TreeHeader/highlighted-text=#ff4040
