######################################################################
# Automatically generated by qmake (2.01a) Sun Aug 31 14:14:13 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += . ../../include
CONFIG += console
QT = core
LIBS += -L../../lib -lircclient-qt
unix:QMAKE_LFLAGS += $${QMAKE_RPATH}../../lib

# Input
SOURCES += main.cpp
