[Theme]
name=Dark
version=1.0
description=A dark Communi theme
maintainer=J-P Nurmi <jpnurmi@gmail.com>

[Resources]
prefix=:/themes/dark

[StyleSheets]
document=:/themes/dark/dark.css
application=:/themes/dark/dark.qss

[QPalette]
alternate-base=
base=
bright-text=
button=
button-text=
dark=
highlight=
highlighted-text=
light=
link=
link-visited=
mid=
midlight=
shadow=
text=
window=
window-text=
TextBrowser/shadow=black
