[Theme]
name=Dark
version=1.0
description=A dark Communi theme
maintainer=J-P Nurmi <jpnurmi@gmail.com>

[Resources]
prefix=:/themes/dark

[StyleSheets]
document=:/themes/dark/dark.css
application=:/themes/dark/dark.qss

[QPalette]
Finder/base=#222222
Finder/highlight=#283ecc
TextDocument/highlight=rgba(64,64,255,64)
TextDocument/midlight=#222222
TextDocument/mid=#444444
TextBrowser/shadow=#000000
