[Theme]
name=Default
version=1.0
description=The default Communi theme
maintainer=J-P Nurmi <jpnurmi@gmail.com>

[Resources]
prefix=:/themes/default

[StyleSheets]
document=:/themes/default/default.css
application=:/themes/default/default.qss

[QPalette]
base=#edf3fe
light=#fdfdfd
dark=#e0e0e0
highlight=#ff8080
highlighted-text=#ff4040
mid=#bec3cb
midlight=#ffffff
shadow=gray
disabled/text=#808080
